### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/RedstoneShark#2]
Forge 2768
RedShark 1.0.1

[crash-2018-11-12_21.55.55-server.txt](https://github.com/Darkhax-Minecraft/RedstoneShark/files/2574597/crash-2018-11-12_21.55.55-server.txt)

**Comment by Darkhax** [comment]
Version 1.0.4 should fix this issue. It will be available on Curse when the curse team approves it.
