### ISSUE TITLE
Crash during startup (server or client)

### ISSUE THREAD

**Issue by L-Clouds** [Darkhax-Minecraft/RedstoneShark#4]
_Forge Mod Loader version 14.23.2.2611 for Minecraft 1.12.2
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_161, running on Windows 7:amd64
redshark(Red Shark:1.0.4): RedShark-1.12.2-1.0.4.jar ()_

Playing an outdated install of Automaton modpack to which I've added a few QoL mods.  Got curious to know what kind of network traffic it would incur if actually played online; decided to give this mod a try, but crashed during load.

Got a crash message very similar to #2 both in client and server processes.  Could be Java version incompatibility?  Could be Forge version incompatibility?  Could be a mod incompatibility?  Could be a bug?  It is a mystery.  Logs attached:

[crash-2019-08-01_05.16.43-client.txt](https://github.com/Darkhax-Minecraft/RedstoneShark/files/3456764/crash-2019-08-01_05.16.43-client.txt)
[fml-client-latest.log](https://github.com/Darkhax-Minecraft/RedstoneShark/files/3456766/fml-client-latest.log)
[crash-2019-08-01_05.10.11-server.txt](https://github.com/Darkhax-Minecraft/RedstoneShark/files/3456769/crash-2019-08-01_05.10.11-server.txt)
[fml-junk-earlystartup.log](https://github.com/Darkhax-Minecraft/RedstoneShark/files/3456778/fml-junk-earlystartup.log)

**Comment by Darkhax** [comment]
Forge changed how their networking works mid version. You're using a very old version of Forge which is not compatible with newer versions of the mod. This mod was updated to the newer Forge in 1.0.4 so you need to use 1.0.3 or earlier.

**Comment by L-Clouds** [comment]
Thanks!  1.0.3 worked.
